apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres-standalone.fullname" . }}
  labels:
    app: {{ include "postgres-standalone.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postgres-standalone.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgres-standalone.name" . }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgresUser }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresPassword }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgresDatabase }}"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "postgres-standalone.fullname" . }}
