apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgress-standalone.fullname" . }}
  labels:
     app: {{ include "postgres-standalone.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
     app: {{ include "postgres-standalone.name" . }}
