apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql-helm.name" . }}-configmap
data:
  postgresql.conf: |-
    listen_addresses = '*'
    port = 5432
  pg_hba.conf: |-
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    host    all             all             0.0.0.0/0               md5

