apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql-helm.name" . }}-deployment
  labels:
    {{- include "postgresql-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgresql-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgresql-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql-helm.name" . }}-secret
                  key: postgresql-password
          volumeMounts:
            - name: {{ include "postgresql-helm.name" . }}-configmap-volume
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
            - name: {{ include "postgresql-helm.name" . }}-configmap-volume
              mountPath: /etc/postgresql/pg_hba.conf
              subPath: pg_hba.conf
      volumes:
        - name: {{ include "postgresql-helm.name" . }}-configmap-volume
          configMap:
            name: {{ include "postgresql-helm.name" . }}-configmap

