apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql-helm.fullname" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}

